# --- STAGE 1: Build Phase ---
FROM node:22-alpine AS builder
WORKDIR /app

# Copy package files first to leverage Docker layer caching
COPY .env ./
COPY package*.json ./
COPY prisma.config.ts ./
COPY prisma ./prisma/

# Install all dependencies (including devDependencies needed for build)
RUN npm ci

# Generate the Prisma Client (creates the rust binaries and types)
RUN npx prisma generate

# Copy the rest of your TypeScript application files
COPY . .

# Compile TypeScript to JavaScript (generates the /app/dist folder)
RUN npm run build

# Remove development dependencies to keep the image slim
RUN npm prune --production


# --- STAGE 2: Production Execution Phase ---
FROM node:22-alpine AS runner
WORKDIR /app

# Set environments
ENV NODE_ENV=production

# Install timezone data for scheduler period resolution
RUN apk add --no-cache tzdata

# Copy only the necessary runtime files from the builder stage
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
# ⚠️ COPIES THE CORRECT OUTDIR FOLDER
COPY --from=builder /app/dist ./dist 
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./ 
COPY --from=builder /app/.env ./ 

# Expose your server port
EXPOSE 3000

# ⚠️ EXECUTES THE EXACT MIRRORED PATH GENERATED BY TSCONFIG
CMD ["sh", "-c", "npx prisma migrate deploy && node dist/src/server.js"]